# Generated by Django 5.2.18 on 2026-10-09 21:57

import django.core.validators
import django.db.models.deletion
import switches.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.GenericIPAddressField(unique=True)),
                ('port', models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('driver', models.CharField(default='juniper_ex', max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('credential_env', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^SWITCH_CREDENTIAL_[A-Z0-9_]+$', 'Use a SWITCH_CREDENTIAL_ environment variable.')])),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('snapshot', switches.fields.EncryptedJSONField(blank=True, default=dict)),
                ('operation_token', models.UUIDField(editable=False, null=True)),
                ('locked_until', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'ordering': ['name', 'pk'],
                'permissions': [('manage_inventory', 'Manage switch inventory'), ('discover_switches', 'Discover switches on approved networks'), ('manage_access', 'Manage per-switch access')],
            },
        ),
        migrations.CreateModel(
            name='ConfigRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', switches.fields.EncryptedTextField()),
                ('checksum', models.CharField(max_length=64)),
                ('source', models.CharField(default='poll', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='switches.switch')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=50)),
                ('driver', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('username', models.CharField(max_length=100)),
                ('credential_env', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^SWITCH_CREDENTIAL_[A-Z0-9_]+$', 'Use a SWITCH_CREDENTIAL_ environment variable.')])),
                ('status', models.CharField(default='queued', max_length=20)),
                ('results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('payload', switches.fields.EncryptedJSONField(default=dict)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('output', switches.fields.EncryptedTextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='switches.switch')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ConfigChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commands', switches.fields.EncryptedTextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('base_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='switches.configrevision')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='switches.switch')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='SwitchAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('operator', 'Operator'), ('admin', 'Administrator')], default='viewer', max_length=10)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='switches.switch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('switch', 'user'), name='unique_switch_access')],
            },
        ),
    ]
