# Generated by Django 5.2.18 on 2026-10-09 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='snmp_credential_env',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^SWITCH_CREDENTIAL_[A-Z0-9_]+$', 'Use a SWITCH_CREDENTIAL_ environment variable.')]),
        ),
        migrations.AddField(
            model_name='switch',
            name='snmp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='switch',
            name='snmp_port',
            field=models.PositiveIntegerField(default=161, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
