# Generated by Django 5.2.18 on 2026-10-09 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0003_alter_discoveryrun_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configchange',
            name='base_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='switches.configrevision'),
        ),
    ]
