# Generated by Django 5.2.18 on 2026-10-10 00:06

import django.core.validators
import django.db.models.deletion
import switches.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switches", "0004_alter_configchange_base_revision"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("username", models.CharField(max_length=100)),
                ("password", switches.fields.EncryptedTextField()),
            ],
            options={
                "ordering": ["name"],
                "permissions": [
                    ("manage_credentials", "Manage shared switch credentials")
                ],
            },
        ),
        migrations.AlterField(
            model_name="discoveryrun",
            name="credential_env",
            field=models.CharField(
                blank=True,
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^SWITCH_CREDENTIAL_[A-Z0-9_]+$",
                        "Use a SWITCH_CREDENTIAL_ environment variable.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="discoveryrun",
            name="username",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="switch",
            name="credential_env",
            field=models.CharField(
                blank=True,
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^SWITCH_CREDENTIAL_[A-Z0-9_]+$",
                        "Use a SWITCH_CREDENTIAL_ environment variable.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="switch",
            name="username",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="discoveryrun",
            name="credential",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="switches.credential",
            ),
        ),
        migrations.AddField(
            model_name="switch",
            name="credential",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="switches.credential",
            ),
        ),
    ]
