# Generated by Django 5.2.18 on 2026-10-10 00:12

from django.db import migrations


def rename_scanning_permission(apps, schema_editor):
    apps.get_model("auth", "Permission").objects.using(schema_editor.connection.alias).filter(
        content_type__app_label="switches", content_type__model="switch",
        codename="discover_switches",
    ).update(name="Scan networks and discover switches")


def restore_permission_name(apps, schema_editor):
    apps.get_model("auth", "Permission").objects.using(schema_editor.connection.alias).filter(
        content_type__app_label="switches", content_type__model="switch",
        codename="discover_switches",
    ).update(name="Discover switches on approved networks")


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("switches", "0005_credential_alter_discoveryrun_credential_env_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="switch",
            options={
                "ordering": ["name", "pk"],
                "permissions": [
                    ("manage_inventory", "Manage switch inventory"),
                    ("discover_switches", "Scan networks and discover switches"),
                    ("manage_access", "Manage per-switch access"),
                ],
            },
        ),
        migrations.RunPython(rename_scanning_permission, restore_permission_name),
    ]
