# Generated by Django 5.2.18 on 2026-10-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switches", "0006_alter_switch_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveryrun",
            name="error",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
