# Generated by Django 5.2.18 on 2026-10-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switches", "0007_discoveryrun_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveryrun",
            name="scanned",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
