# Generated by Django 5.2.18 on 2026-10-10 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switches", "0008_discoveryrun_scanned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustedHostKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.GenericIPAddressField()),
                ("port", models.PositiveIntegerField()),
                ("algorithm", models.CharField(max_length=100)),
                ("public_key", models.TextField()),
                ("trusted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trusted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("address", "port"), name="unique_trusted_host"
                    )
                ],
            },
        ),
    ]
